version: '3'

services:
  mongodb:
    image: mongo:bionic
    ports:
      - "27017:27017"
    networks:
      - mynetwork
    volumes:
      - mongodb_data:/data/db

networks:
  mynetwork:

volumes:
  mongodb_data:
